name: Dummy Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate deployment process
        run: |
          echo "Starting deployment..."
          sleep 3
          echo "Code deployed successfully 🚀"
